### ISSUE TITLE
Adding user-friendly report

### ISSUE THREAD

**Issue by Accio** [bedapub/HBVouroboros#4]
Use Rmarkdown and/or Jupyter ntoebook to add a user-friendly report, which include

* mapping statistics
* genotyping 
* visualization of  genomes and features
* SNP/SV information

See the biokit pipeline for inspirations

**Comment by DingailuM** [comment]
Hi David,
I can help generate the report :)

**Comment by Accio** [comment]
Thanks @DingailuM! I am now working on #2. i will give a green light as soon as I finish with that, because it's probably easier if the package structure becomes stable.
